name: udoit
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"
  # changed due to waitfor.dart specifities
  #sdk: ">=2.12.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter

  #js: ^0.6.2

  #splashscreen: ^1.3.3

  cupertino_icons: ^1.0.0
  #url_launcher: 5.7.5
  #url_launcher: ^5.7.10
  #url_launcher_linux: 0.0.1+1
  #url_launcher_linux: ^0.0.1+4

  #url_launcher_windows: 0.0.1+1
  #url_launcher_macos: 0.0.1+8
  
  #url_launcher_web: 0.1.4+1
  #url_launcher_web: ^0.1.5
  
  nb_utils: 3.2.9
  google_fonts: 1.1.0
  animations: 1.1.2
  intl: 0.16.1
  http: 0.12.2
  #firebase_core: 0.5.0+1
  firebase_core: 0.5.3
  #firebase_core_web: 0.2.0
  firebase_core_web: 0.2.1+1
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.2.0
  firebase_image: ^0.3.0

  #firebase_analytics: 6.0.2 #removed due to issues with Web builds
  #firebase_analytics_web: 0.1.1 #removed due to issues with Web builds
  #firebase_analytics_platform_interface: 1.0.3 #removed due to issues with Web builds
  firebase_crashlytics: 0.1.4+1
  html: 0.14.0+3
  share: 0.6.5
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_vector_icons: 0.2.1
  package_info: 0.4.3

  flutter_statusbarcolor: 0.2.3
  simple_animations: 1.3.8
  snaplist: 0.1.8
  flutter_svg: ^0.19.2+1
  flutter_slidable: 0.5.7
  flutter_staggered_grid_view: 0.3.2
  flutter_staggered_animations: 0.1.2

  google_sign_in: 4.5.3
  geolocator: 5.3.2+2
  geocoder: 0.2.1
  google_maps_flutter: 0.5.21+3
  #google_maps_flutter_web: 0.1.0+2
  clustering_google_maps: 0.1.2
  #razorpay_flutter: 1.2.2
  signature: 3.2.0
  liquid_swipe: 1.5.0
  lipsum: 1.0.1
  flutter_colorpicker: 0.3.4
  clippy_flutter: 1.1.1
  flutter_tags: ^0.4.8
  image_picker_gallery_camera: 0.1.6
  #video_player: 0.10.11+2

  charts_flutter: ^0.9.0
  flutter_reaction_button: ^1.0.1
  lottie: ^0.6.0
  showcaseview: ^0.1.6
  date_utils: ^0.1.0+3
  cached_network_image: ^2.3.1
  local_auth: ^0.6.3+1
  #admob_flutter: 1.0.0
  dots_indicator: ^0.0.4
  #firebase_picture_uploader: ^1.1.2
  image_picker: ^0.6.7+14
  #flutter_web_image_picker: ^0.0.2
  #ext_video_player: ^0.0.3
  youtube_player_iframe: ^1.1.0
  
  english_words: ^3.1.5
  flutter_signin_button: ^1.1.0
  firebase_auth: ^0.18.4+1
  flutter_facebook_login:
    git:
      url: https://github.com/romulojjunior/flutter_facebook_login.git
      ref: v1.3.0-web
  #flutter_twitter_login
  flutter_html: ^1.1.1
  #flutter_summernote: ^0.2.2
  #easy_web_view: ^1.3.1
  #webview_flutter: ^1.0.7

  flutter_localizations:
    sdk: flutter

dependency_overrides:
#  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner: ^1.9.0
  #flutter packages pub run build_runner build

flutter:

  uses-material-design: true

  assets:
    - assets/splashscreen/splashscreen_1.jpeg
    # - assets/splashscreen/3.0x/splashscreen_1.jpeg
    - assets/splashscreen/splashscreen_2.jpeg
    - assets/walkthrough/
    - assets/logo/
    - assets/categories/
    - assets/signinup/
    - assets/newSmartMob/
    - assets/icons/
    - assets/profiles/
    - assets/initiatives/

    - assets/prokit/LikeButton/image/grey.jpg
    - assets/prokit/integrations/map_point.json
    - assets/prokit/defaultTheme/
    - lang/en.json
    - lang/hi.json

    #- assets/
    #- images/smartDeck/images/
    #- images/smartDeck/images/sdchats.png
    #- images/smartDeck/images/sdupdate.png
    #- images/Reaction/images/
    #- images/Reaction/images/SocialMedia/
    #- images/Tinder/images/
    ##### - images/LikeButton/image/grey.jpg
    #- assets/integrations/lang/
    #- assets/shophop_data/
    #- images/app/icons/
    #- images/app/
    #- images/app/ic_rate_app.png
    #- images/theme1/
    #~- images/theme2/
    #- images/theme3/
    #####- images/theme4/
    #- images/theme5/
    #- images/theme6/
    #- images/theme7/
    #- images/theme8/
    #- images/theme9/
    #- images/theme10/
    #- images/theme11/
    #- images/theme12/
    #- images/Theme13/
    #- images/theme12/mastercard.png
    #- images/dashboard/
    #- images/qibus/
    #- images/learner/
    #- images/social/
    #- images/quiz/
    #- images/food/
    #- images/grocery/
    #- images/integrations/icons/
    #- images/integrations/img/
    #- images/shophop/
    #-images/shophop/radar.gif
    #-images/shophop/img/products/
    #-images/shophop/img/products/decor/
    #-images/shophop/img/products/dress/
    #-images/shophop/img/products/shoes/
    #-images/shophop/img/products/banners/b1.jpg
    #-images/shophop/img/products/banners/b2.jpg
    #-images/shophop/img/products/banners/b3.jpg
    #-images/shophop/img/products/banners/b4.jpg
    #-images/shophop/img/products/banners/b5.jpg
    #-images/shophop/img/products/banners/b6.jpg
    #-images/theme12/
    #-images/theme12/mastercard.png
    #-images/orapay/
    #-images/muvi/icons/
    #-images/muvi/images/
    #-images/widgets/materialWidgets/mwAppStructureWidgets/BottomNavigation/
    #-images/widgets/materialWidgets/mwAppStructureWidgets/TabBar/
    #-images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    #-images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    #-images/widgets/materialWidgets/mwInformationDisplayWidgets/cards/
    #-images/widgets/materialWidgets/mwInformationDisplayWidgets/gridview/
    #-images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    #-images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    #-images/widgets/materialWidgets/mwLayoutWidgtes/MWUserAccountDrawerHeaderWidget/
    #-images/widgets/materialWidgets/mwDialogAlertPanelWidgets/
    #-images/widgets/materialWidgets/mwLayoutWidgtes/MWListTile/
    #-images/widgets/cupertinoWidgets/
    #-images/widgets/materialWidgets/mwInformationDisplayWidgets/listView/
    #-images/widgets/animationAndMotionWidgets/
    #-images/widgets/paintingAndEffectWidgets/opacity/
    #-images/widgets/interactionModelWidgets/
    #-images/defaultTheme/
    #-images/defaultTheme/category/
    #-images/defaultTheme/banner/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

